# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/pll_27MHz/pll_27MHz.xci
# IP: The module: 'pll_27MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/pll_27MHz/pll_27MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_27MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/pll_27MHz/pll_27MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_27MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/pll_27MHz/pll_27MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_27MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/pll_27MHz/pll_27MHz.xci
# IP: The module: 'pll_27MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/pll_27MHz/pll_27MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_27MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/pll_27MHz/pll_27MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_27MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/pll_27MHz/pll_27MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_27MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
