# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# IP: ip/ila_256/ila_256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_256 || ORIG_REF_NAME==ila_256} -quiet] -quiet
