# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ddc_edid_rom/ddc_edid_rom.xci
# IP: The module: 'ddc_edid_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ddc_edid_rom/ddc_edid_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_edid_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ddc_edid_rom/ddc_edid_rom.xci
# IP: The module: 'ddc_edid_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ddc_edid_rom/ddc_edid_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_edid_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
