# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ila_64/ila_64.xci
# IP: The module: 'ila_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ila_64/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ila_64/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ila_64/ila_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ila_64/ila_64.xci
# IP: The module: 'ila_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ila_64/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ila_64/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_project/Xilinx/DMA_201C_V1.0/project/project.srcs/sources_1/ip/ila_64/ila_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
